import os
os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "false"
os.environ["XLA_PYTHON_CLIENT_MEM_FRACTION"] = ".2"

# use `ulimit -n 4096` beforehand to increase the number of files that can be opened by one process

import resource
resource.setrlimit(resource.RLIMIT_CORE, (resource.RLIM_INFINITY, resource.RLIM_INFINITY))

env_cls = "PianoJointPD"
env_params = dict(
    fps = 60,
    frameskip=8,
    control_freq=1,
    episode_length = 30*5,
    contactable_links = None,

    goal_reward_weight = [0.4, 0.4],

    importance_sampling = 0,
    importance_discount = 0.95,
    importance_decay = 0.5,
    importance_scale = 8,

    character_model = "assets/two_hands_ds6.5_joint_driven.xml",

    key_links = [
        "L:ulna",
        "L:radius",
        "L:lunate",
        "L:scaphoid",
        "L:pisiform",
        "L:triquetrum",
        "L:capitate",
        "L:trapezium",
        "L:firstmc",
        "L:proximal_thumb",
        "L:distal_thumb",
        "L:THtip",
        "L:trapezoid",
        "L:hamate",
        "L:secondmc",
        "L:proxph2",
        "L:midph2",
        "L:distph2",
        "L:IFtip",
        "L:thirdmc",
        "L:proxph3",
        "L:midph3",
        "L:distph3",
        "L:MFtip",
        "L:fourthmc",
        "L:proxph4",
        "L:midph4",
        "L:distph4",
        "L:RFtip",
        "L:fifthmc",
        "L:proxph5",
        "L:midph5",
        "L:distph5",
        "L:LFtip"

        "R:ulna",
        "R:radius",
        "R:lunate",
        "R:scaphoid",
        "R:pisiform",
        "R:triquetrum",
        "R:capitate",
        "R:trapezium",
        "R:firstmc",
        "R:proximal_thumb",
        "R:distal_thumb",
        "R:THtip",
        "R:trapezoid",
        "R:hamate",
        "R:secondmc",
        "R:proxph2",
        "R:midph2",
        "R:distph2",
        "R:IFtip",
        "R:thirdmc",
        "R:proxph3",
        "R:midph3",
        "R:distph3",
        "R:MFtip",
        "R:fourthmc",
        "R:proxph4",
        "R:midph4",
        "R:distph4",
        "R:RFtip",
        "R:fifthmc",
        "R:proxph5",
        "R:midph5",
        "R:distph5",
        "R:LFtip"
    ],
    ob_horizon = 2,
    global_pos = True,
)

training_params = dict(
    max_epochs =    200000,
    save_interval =  20000,
    horizon = 8,
    num_envs = 2048,
    terminate_reward = -25
)

model_params = dict(
    init_sigma = 0.5,
    max_sigma = 0.5,
    normalizer_scale = 3,
    latent_dim = 256,
    normalize_latent = False,
    normalize_value = False
)

discriminators = {
    "left_wrist" : dict(
        key_links = [
            "L:ulna",
            "L:radius",
            "L:lunate",
            # "L:scaphoid",
            # "L:pisiform",
            # "L:triquetrum",
            # "L:capitate",
            # "L:trapezium",
            # "L:firstmc",
            # "L:proximal_thumb",
            # "L:distal_thumb",
            # "L:THtip",
            # "L:trapezoid",
            # "L:hamate",
            # "L:secondmc",
            # "L:proxph2",
            # "L:midph2",
            # "L:distph2",
            # "L:IFtip",
            # "L:thirdmc",
            # "L:proxph3",
            # "L:midph3",
            # "L:distph3",
            # "L:MFtip",
            # "L:fourthmc",
            # "L:proxph4",
            # "L:midph4",
            # "L:distph4",
            # "L:RFtip",
            # "L:fifthmc",
            # "L:proxph5",
            # "L:midph5",
            # "L:distph5",
            # "L:LFtip"
        ],
        global_pos = True,
        weight = 0.05/2,
        motion_file=[os.path.join("motions/left_hand_motions", _) for _ in os.listdir("motions/left_hand_motions")],
    ),
    "left_fingers" : dict(
        key_links = [
            # "L:ulna",
            # "L:radius",
            # "L:lunate",
            # "L:scaphoid",
            # "L:pisiform",
            # "L:triquetrum",
            # "L:capitate",
            "L:trapezium",
            "L:firstmc",
            "L:proximal_thumb",
            "L:distal_thumb",
            "L:THtip",
            "L:trapezoid",
            "L:hamate",
            "L:secondmc",
            "L:proxph2",
            "L:midph2",
            "L:distph2",
            "L:IFtip",
            "L:thirdmc",
            "L:proxph3",
            "L:midph3",
            "L:distph3",
            "L:MFtip",
            "L:fourthmc",
            "L:proxph4",
            "L:midph4",
            "L:distph4",
            "L:RFtip",
            "L:fifthmc",
            "L:proxph5",
            "L:midph5",
            "L:distph5",
            "L:LFtip"
        ],
        parent_link = "L:lunate",
        weight = 0.15/2,
        motion_file=[os.path.join("motions/left_hand_motions", _) for _ in os.listdir("motions/left_hand_motions")],
    ),
    "right_wrist" : dict(
        key_links = [
            "R:ulna",
            "R:radius",
            "R:lunate",
            # "R:scaphoid",
            # "R:pisiform",
            # "R:triquetrum",
            # "R:capitate",
            # "R:trapezium",
            # "R:firstmc",
            # "R:proximal_thumb",
            # "R:distal_thumb",
            # "R:THtip",
            # "R:trapezoid",
            # "R:hamate",
            # "R:secondmc",
            # "R:proxph2",
            # "R:midph2",
            # "R:distph2",
            # "R:IFtip",
            # "R:thirdmc",
            # "R:proxph3",
            # "R:midph3",
            # "R:distph3",
            # "R:MFtip",
            # "R:fourthmc",
            # "R:proxph4",
            # "R:midph4",
            # "R:distph4",
            # "R:RFtip",
            # "R:fifthmc",
            # "R:proxph5",
            # "R:midph5",
            # "R:distph5",
            # "R:LFtip"
        ],
        global_pos = True,
        key_link_index_offset = -34, # the offset remove the left hand links when fetching reference motions
        weight = 0.05/2,
        motion_file=[os.path.join("motions/right_hand_motions", _) for _ in os.listdir("motions/right_hand_motions")],
    ),
    "right_fingers" : dict(
        key_links = [
            # "R:ulna",
            # "R:radius",
            # "R:lunate",
            # "R:scaphoid",
            # "R:pisiform",
            # "R:triquetrum",
            # "R:capitate",
            "R:trapezium",
            "R:firstmc",
            "R:proximal_thumb",
            "R:distal_thumb",
            "R:THtip",
            "R:trapezoid",
            "R:hamate",
            "R:secondmc",
            "R:proxph2",
            "R:midph2",
            "R:distph2",
            "R:IFtip",
            "R:thirdmc",
            "R:proxph3",
            "R:midph3",
            "R:distph3",
            "R:MFtip",
            "R:fourthmc",
            "R:proxph4",
            "R:midph4",
            "R:distph4",
            "R:RFtip",
            "R:fifthmc",
            "R:proxph5",
            "R:midph5",
            "R:distph5",
            "R:LFtip"
        ],
        parent_link = "R:lunate",
        key_link_index_offset = -34, # the offset remove the left hand links when fetching reference motions
        weight = 0.15/2,
        motion_file=[os.path.join("motions/right_hand_motions", _) for _ in os.listdir("motions/right_hand_motions")],
    )
}
